### ISSUE TITLE
Style Color for Light and Dark Theme

### ISSUE THREAD

**Issue by zillBoy** [harshzalavadiya/react-multi-select-component#446]
I have the value for light and dark themes, but I don't know how to override them into CSS files, because I have the value in javascript.
Possible Solution: If I had a **styles** props then things would have been much easier!

**Comment by harshzalavadiya** [comment]
@zillBoy 

Overriding styles are easy, you just have to use prefers color scheme property and it should work as expected

```css
/* Light Styles */
.rmsc {
  --rmsc-main: #4285f4!important;
  --rmsc-hover: #f1f3f5!important;
  --rmsc-selected: #e2e6ea!important;
  --rmsc-border: #ccc!important;
  --rmsc-gray: #aaa!important;
  --rmsc-bg: #fff!important;
  --rmsc-p: 10px!important;
  --rmsc-radius: 4px!important;
  --rmsc-h: 38px!important;
}

/* Dark Styles */
@media (prefers-color-scheme: dark) {
  /* If you are using some UI library then according to it's dark mode class you can change this */
  .rmsc {
    --rmsc-main: red!important;
    --rmsc-hover: #f1f3f5!important;
    --rmsc-selected: #e2e6ea!important;
    --rmsc-border: #ccc!important;
    --rmsc-gray: #aaa!important;
    --rmsc-bg: #fff!important;
    --rmsc-p: 10px!important;
    --rmsc-radius: 4px!important;
    --rmsc-h: 38px!important;
  }
}
```

As you are saying you are getting this from javascript you can even do something like this in your choice of framework

```jsx
const defaultProps = {
  main: "#4285f4",
  hover: "#f1f3f5",
  selected: "#e2e6ea",
  border: "#ccc",
  gray: "#aaa",
  bg: "#fff",
  p: "10px",
  radius: "4px",
  h: "38px"
};

const generateTheme = (colors) => {
  const finalColors = { ...defaultProps, ...colors };
  const prefix = ".rmsc{\n";
  const posfix = "}\n";
  let content = "";
  for (const [key, value] of Object.entries(finalColors)) {
    content = `${content}--rmsc-${key}: ${value};\n`;
  }
  return prefix + content + posfix;
};

export const buildStyles = (light, dark = {}) => {
  const darkPrefix = `\n@media (prefers-color-scheme: dark) {\n`;
  const darkPostfix = `}`;
  const lightColors = generateTheme(light);
  const darkColors = generateTheme(dark);
  return lightColors + darkPrefix + darkColors + darkPostfix;
};
```

and then use it like this in your component

```jsx
  const styles = useMemo(() => buildStyles({}, { main: "red" }), []);

  return (
    <div>
      <style key="rmsc-styles" children={styles} />
      ... your component
```

[![Edit rmsc-dark-mode](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rmsc-dark-mode-9jfhk?fontsize=14&hidenavigation=1&theme=dark)
