### ISSUE TITLE
how to set search icon with search text?

### ISSUE THREAD

**Issue by swathithayalan** [harshzalavadiya/react-multi-select-component#61]

**Comment by harshzalavadiya** [comment]
@swathithayalan,

Did you mean for search text box?
if so then this component do not support custom icon for search textbox but you can have emoji as icon like below

```jsx
overrideStrings={{ "search": "🔍 Search" }}
```

![image](https://user-images.githubusercontent.com/5774849/86136289-86452680-bb09-11ea-9337-42a0f90ba4d7.png)

**Comment by swathithayalan** [comment]
> @swathithayalan,
> 
> Did you mean for search text box?
> if so then this component do not support custom icon for search textbox but you can have emoji as icon like below
> 
> ```js-jsx
> overrideStrings={{ "search": "🔍 Search" }}
> ```
> 
> ![image](https://user-images.githubusercontent.com/5774849/86136289-86452680-bb09-11ea-9337-42a0f90ba4d7.png)

can we get support to render svg or fontawesome icons instead of emojis?

**Comment by harshzalavadiya** [comment]
@swathithayalan,

As of now I'm not planning to add svg icon support directly since it will just increase size for package

If you want to use svg icon you can customize input element via CSS quick version below

![image](https://user-images.githubusercontent.com/5774849/86223365-15ebe300-bba5-11ea-95f6-1594f9c92c0b.png)

```css
.select-panel > div{
  position: relative;
}

.select-panel > div::before{
  content: url("https://unpkg.com/material-design-icons@3.0.1/action/svg/production/ic_search_24px.svg");
  position: absolute;
  width: 2rem;
  top: 0;
  left: 0;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

.select-panel input[type="search"]{
  padding-left: 2rem;
}
```
